spring:
  application:
    name: files-management-app
  main:
    banner-mode: off
  datasource:
    url:
    username:
    password:

minio:
  url: http://localhost:9000
  access :
      name: admin
      secret: StrongPassword123
