spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

minio:
  url: ${MINIO_URL}
  access:
    name: ${MINIO_ACCESS_NAME}
    secret: ${MINIO_ACCESS_SECRET}
